-- Issue #59: custom/generic user-defined obligations, beyond the 3 hardcoded ones.

CREATE TABLE custom_obligation (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(255) NOT NULL,
    due_date           DATE NOT NULL,
    -- NULL = one-off (the user re-edits due_date themselves once handled, same as
    -- work_pass.expiry_date); set = recurs every N months from due_date, the same anchor-date
    -- recurrence RuleEngine.nextAcraDeadline already uses for ACRA, just a configurable step
    -- instead of a fixed 12 months.
    recurrence_months  INT,
    business_id        BIGINT NOT NULL REFERENCES business(id) ON DELETE CASCADE
);

-- Same reasoning as V3 - deleting a business must remove its custom obligations too, at the DB
-- level, correct regardless of which code path ever deletes a business row.

-- Postgres never auto-indexes a foreign key column on the referencing side (issue #50's own
-- finding) - indexed here from the start instead of waiting to discover the gap later.
CREATE INDEX idx_custom_obligation_business_id ON custom_obligation (business_id);

-- deadline_record needs to be able to represent a CUSTOM obligation too, and (unlike the 3
-- built-in types, which are one-per-business-per-type at any given moment) a business can have
-- several custom obligations that happen to share the same due_date - the existing
-- (business_id, obligation_type, due_date) dedupe key the sync job relies on can't tell those
-- apart. custom_obligation_id is the real disambiguator; custom_name is denormalized onto the
-- record itself so a reminder email/log line never needs an extra join just to render.
ALTER TABLE deadline_record ADD COLUMN custom_obligation_id BIGINT REFERENCES custom_obligation(id) ON DELETE CASCADE;
ALTER TABLE deadline_record ADD COLUMN custom_name VARCHAR(255);
CREATE INDEX idx_deadline_record_custom_obligation_id ON deadline_record (custom_obligation_id);

ALTER TABLE deadline_record DROP CONSTRAINT deadline_record_obligation_type_check;
ALTER TABLE deadline_record ADD CONSTRAINT deadline_record_obligation_type_check
    CHECK (obligation_type IN ('ACRA_ANNUAL_RETURN', 'GST_F5', 'WORK_PASS_RENEWAL', 'CUSTOM'));
