-- Issue #34: let a user manually mark a specific deadline as handled/dismissed, independent of
-- deadline_record.reminder_sent (which only ever means "the automated reminder pipeline actually
-- sent this one" - not the same thing as "a human already dealt with it"). GET
-- /businesses/{id}/deadlines is entirely live-computed by RuleEngine with no persisted row (or
-- id) to attach a flag to - and a deadline_record row for what's currently on screen may not
-- even exist yet, since the sync job that creates them only runs once a day. Matched by natural
-- key instead (business_id, obligation_type, due_date, custom_obligation_id), the same shape
-- deadline_record's own dedupe check already uses, independent of whether a deadline_record row
-- exists.

CREATE TABLE dismissed_deadline (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id           BIGINT NOT NULL REFERENCES business(id) ON DELETE CASCADE,
    obligation_type       VARCHAR(255) NOT NULL
        CHECK (obligation_type IN ('ACRA_ANNUAL_RETURN', 'GST_F5', 'WORK_PASS_RENEWAL', 'CUSTOM')),
    due_date              DATE NOT NULL,
    -- Same disambiguator as deadline_record.custom_obligation_id (V11) - NULL for the 3
    -- built-in types, set for CUSTOM, since two different custom obligations on the same
    -- business can share a due date.
    custom_obligation_id  BIGINT REFERENCES custom_obligation(id) ON DELETE CASCADE,
    custom_name           VARCHAR(255),
    dismissed_at          TIMESTAMP NOT NULL
);

-- Postgres never auto-indexes a foreign key column on the referencing side (issue #50's own
-- finding) - indexed here from the start instead of waiting to discover the gap later.
CREATE INDEX idx_dismissed_deadline_business_id ON dismissed_deadline (business_id);
CREATE INDEX idx_dismissed_deadline_custom_obligation_id ON dismissed_deadline (custom_obligation_id);

-- No DB-level uniqueness constraint on the natural key, deliberately - deadline_record itself
-- has none either (see DeadlineRecordRepository's own comment); a duplicate dismiss row under a
-- genuine race is a harmless no-op (the deadline is still dismissed either way), not worth the
-- extra complexity a nullable-column-safe unique constraint would need.
