-- Baseline schema, matching what Hibernate's ddl-auto=update had already generated in dev.
-- From here on, Flyway owns schema changes (spring.jpa.hibernate.ddl-auto=validate only
-- checks the schema matches the entities, never mutates it) - see issue #7.

CREATE TABLE business (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255),
    financial_year_end  DATE,
    gst_registered      BOOLEAN NOT NULL
);

CREATE TABLE work_pass (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name  VARCHAR(255),
    expiry_date    DATE,
    business_id    BIGINT REFERENCES business(id)
);

CREATE TABLE deadline_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id      BIGINT REFERENCES business(id),
    obligation_type  VARCHAR(255) NOT NULL
        CHECK (obligation_type IN ('ACRA_ANNUAL_RETURN', 'GST_F5', 'WORK_PASS_RENEWAL')),
    due_date         DATE,
    reminder_sent    BOOLEAN NOT NULL DEFAULT FALSE
);
