-- Adds real authentication (issue #19). Existing business rows were test/portfolio data only
-- (no real users), cleared before this migration so owner_id can be NOT NULL from the start
-- rather than needing a nullable-then-backfill-then-constrain dance.

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);

ALTER TABLE business ADD COLUMN owner_id BIGINT NOT NULL REFERENCES app_user(id);
