-- Idempotency key support for POST /api/businesses (issue #61) - a network retry after a
-- timeout (the request actually succeeded server-side, but the client never saw the response)
-- could otherwise create a duplicate business. The unique constraint on
-- (idempotency_key, owner_id) is the real enforcement point under concurrency, not just the
-- application-level lookup before insert - same "check first, DB constraint is the actual
-- guarantee" shape already used for issue #42's registration race.

CREATE TABLE idempotency_key (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(255) NOT NULL,
    owner_id        BIGINT NOT NULL REFERENCES app_user(id),
    business_id     BIGINT NOT NULL REFERENCES business(id),
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_idempotency_key_owner UNIQUE (idempotency_key, owner_id)
);
