-- Password reset flow (issue #37) - a single-use, expiring token generated on
-- POST /api/auth/forgot-password and consumed by POST /api/auth/reset-password.

CREATE TABLE password_reset_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(255) NOT NULL UNIQUE,
    user_id    BIGINT NOT NULL REFERENCES app_user(id),
    expires_at TIMESTAMP NOT NULL
);
