-- Email verification on registration (issue #36) - proves the registrant actually owns the
-- email address they registered with, via the same single-use expiring token shape already
-- used for password reset (issue #37).

ALTER TABLE app_user ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE email_verification_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(255) NOT NULL UNIQUE,
    user_id    BIGINT NOT NULL REFERENCES app_user(id),
    expires_at TIMESTAMP NOT NULL
);
